### ISSUE TITLE
Input language is not properly determined on Linux OS

### ISSUE THREAD

**Issue by demoth** [siropkin/kursor#1]
On my system the language displayed with the Kursor is always `en`.

CapsLock is however properly displayed.

I assume `getLocale` may not work on all systems: 
https://docs.oracle.com/javase/7/docs/api/java/awt/im/InputContext.html#getLocale()

>  Not all host operating systems provide API to determine the locale of the currently selected native input method or keyboard layout, and to select a native input method or keyboard layout by locale. For host operating systems that don't provide such API, selectInputMethod assumes that native input methods or keyboard layouts provided by the host operating system support only the system's default locale. 

My system details
Ubuntu 22.10, Gnome
IntelliJ IDEA 2023.1.3 (Ultimate Edition)
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by siropkin** [comment]
Thanks for the report! I will take a look and try to find a solution. (Issue #1 🎉)

**Comment by iNgredie** [comment]
The same problem.
![image](https://github.com/siropkin/kursor/assets/65018503/e2140d9d-720d-497b-b257-e19f03bc2ae2)

**Comment by siropkin** [comment]
Ok, guys, i found the solution of this issue. 
This is not the ideal solution because it involves executing a shell command to know the current keyboard layout which might affect the performance but it is the only solution I found that works on Linux.
I tested it under Ubuntu 22.04.2 and it worked pretty well but to be honest, I'm not a Linux user so maybe I missed something here...
Anyway, the code and plugin distrib are updated, but it will take a few days until JetBrains finishes its review.

**Comment by siropkin** [comment]
Version 1.0.1 of the Kursor plugin has been approved by JetBrains and is now publicly available at the following link: https://plugins.jetbrains.com/plugin/22072-kursor/versions/stable/360857.

@demoth @iNgredie pls try the new version, appreciate your feedback!

**Comment by demoth** [comment]
@siropkin Nice! Thanks for addressing this. I have however some doubts it will work in KDE (I can check later)

**Comment by iNgredie** [comment]
![image](https://github.com/siropkin/kursor/assets/65018503/a35f4008-ce24-43e2-b06f-9efc551a3982)
![image](https://github.com/siropkin/kursor/assets/65018503/5ce46c6d-48da-46cd-b1e4-aec00d468299)

Doens't work for me :(

**Comment by siropkin** [comment]
@iNgredie thanks for the feedback, i'll try to find the solution for Linux Mint too.

**Comment by siropkin** [comment]
Looks like I found one more solution which will work in Linux Mint (and I believe in other distributions except for Ubuntu). 
There is one problem with this solution: it will not work properly if there are more than two keyboard layouts but hope this is a rare case.
Anyways, now Kursor works in Ubuntu and (at least) in Linux Mint.
Fix is in Kursor v 1.0.3
