### ISSUE TITLE
Could you please support Squirrel Method in MacOS

### ISSUE THREAD

**Issue by Muscleape** [siropkin/kursor#18]
the github address of Squirrel Method

https://github.com/rime/squirrel

**Comment by siropkin** [comment]
Sure! Let me check if I can do that

**Comment by siropkin** [comment]
Okey, I finally did it - add support for Squirrel Method - but I need your help with short names for Squirrel Method.
But first let me describe what I did to make sure I did it right.
1. I installed Squirrel Method for MacOS from here: https://rime.im
2. In MacOS settings I added two new Keyboard layouts: Squirrel - Simplified and Squirrel - Traditional.
3. Now I can choose them:
<img width="260" alt="image" src="https://github.com/user-attachments/assets/8c3ce22b-dfda-4288-b4f3-8b512e7f3f68">

If it is correct then the question for you is how to display them with two/three letters.
My idea is:
- SS for Squirrel - Simplified
<img width="312" alt="image" src="https://github.com/user-attachments/assets/586b9115-edec-407e-8353-8b3c7863ea19">

- ST for Squirrel - Traditional
<img width="307" alt="image" src="https://github.com/user-attachments/assets/7d549b9d-fbfd-4a28-9af1-e17a29ddbda4">


What do you think?

**Comment by siropkin** [comment]
Or it should be ZH for both? Or TW for traditional and CN for simplified?

**Comment by Muscleape** [comment]
i think ZH is better

**Comment by siropkin** [comment]
Great! Then ZH. Thanks!

**Comment by siropkin** [comment]
Fixed in v1.4.1
