### ISSUE TITLE
MacOS. Определение вариантов раскладки

### ISSUE THREAD

**Issue by Ildar7sins** [siropkin/kursor#20]
При работе с типом раскладки "Русска - ПК" на MacOS тип языка не меняется и постоянно остаётся только US, можно ли это поправить?

<img width="231" alt="image" src="https://github.com/user-attachments/assets/139d83c8-23b6-487a-8093-158db56f17d1">

Спасибо за плагин, очень крутой!

**Comment by siropkin** [comment]
Я пофиксил в дев ветке, в ближайшую неделю выпущу новую версию и как выпущу я сообщу.
Спасибо за обратную связь!

**Comment by Ildar7sins** [comment]
Супер, спасибо большое, буду ждать)

**Comment by siropkin** [comment]
Fixed in v1.4.1
