### ISSUE TITLE
When switching to UA keyboard the Kursor shows US

### ISSUE THREAD

**Issue by IVoyt** [siropkin/kursor#30]

**Comment by siropkin** [comment]
Hi! Thanks for reporting the issue. Can you please provide information about OS and exact keyboard layout settings (screenshot of the setting will help a lot)

**Comment by IVoyt** [comment]
## macOS 15.1

<img width="792" alt="Снимок экрана 2024-11-06 в 10 23 58" src="https://github.com/user-attachments/assets/f2e9c3fa-e440-410a-adf6-2bab64600993">

Here is the proof that in UA (ukrainian) layout the Kursor's symbol is incorrect while in other languages it has proper appearance.

<img width="707" alt="Снимок экрана 2024-11-06 в 10 25 00" src="https://github.com/user-attachments/assets/22b15fec-068b-4061-ba10-644aa2220880">

<img width="508" alt="Снимок экрана 2024-11-06 в 10 24 47" src="https://github.com/user-attachments/assets/05ca7d56-ebcb-4f8c-b748-b78bb2d13e68">


#### I do not exactly understand what do you mean saying "provide keyboard layout settings". Did you mean this?

<img width="741" alt="image" src="https://github.com/user-attachments/assets/c7066707-f439-42b5-89bc-f8d450587b97">

**Comment by siropkin** [comment]
Got it, thanks! Working on fix

**Comment by siropkin** [comment]
Fixed in v1.4.2, the version will be available soon. Thanks for the feedback!

**Comment by siropkin** [comment]
Kursor v1.4.2 released
